
import { useMemo } from 'react';
import { useAppLogic } from './useAppLogic';
import { CANVAS_SYSTEM_PROMPT, BBOX_SYSTEM_PROMPT } from '../../constants/appConstants';
import { getShortcutDisplay } from '../../utils/shortcutUtils';

export const useAppProps = (logic: ReturnType<typeof useAppLogic>) => {
  const {
    appSettings,
    chatState,
    uiState,
    pipState,
    eventsState,
    dataManagement,
    currentTheme,
    language,
    t,
    sessionTitle,
    handleSaveSettings,
    handleLoadCanvasPromptAndSave,
    handleToggleBBoxMode,
    handleSuggestionClick,
    handleSetThinkingLevel,
    getCurrentModelDisplayName,
    setIsExportModalOpen,
    isExportModalOpen,
    handleExportChat,
    exportStatus,
    handleOpenSidePanel,
  } = logic;

  // Sidebar Props
  const sidebarProps = useMemo(() => ({
    isOpen: uiState.isHistorySidebarOpen,
    onToggle: () => uiState.setIsHistorySidebarOpen(prev => !prev),
    sessions: chatState.savedSessions,
    groups: chatState.savedGroups,
    activeSessionId: chatState.activeSessionId,
    loadingSessionIds: chatState.loadingSessionIds,
    generatingTitleSessionIds: chatState.generatingTitleSessionIds,
    onSelectSession: (id: string) => chatState.loadChatSession(id, chatState.savedSessions),
    onNewChat: () => chatState.startNewChat(),
    onDeleteSession: chatState.handleDeleteChatHistorySession,
    onRenameSession: chatState.handleRenameSession,
    onTogglePinSession: chatState.handleTogglePinCurrentSession,
    onDuplicateSession: chatState.handleDuplicateSession,
    onOpenExportModal: () => setIsExportModalOpen(true),
    onAddNewGroup: chatState.handleAddNewGroup,
    onDeleteGroup: chatState.handleDeleteGroup,
    onRenameGroup: chatState.handleRenameGroup,
    onMoveSessionToGroup: chatState.handleMoveSessionToGroup,
    onToggleGroupExpansion: chatState.handleToggleGroupExpansion,
    onOpenSettingsModal: () => uiState.setIsSettingsModalOpen(true),
    onOpenScenariosModal: () => uiState.setIsPreloadedMessagesModalOpen(true),
    themeColors: currentTheme.colors,
    t,
    themeId: currentTheme.id,
    language,
    newChatShortcut: getShortcutDisplay('general.newChat', appSettings),
  }), [
    uiState.isHistorySidebarOpen, chatState.savedSessions, chatState.savedGroups, chatState.activeSessionId,
    chatState.loadingSessionIds, chatState.generatingTitleSessionIds, currentTheme, language, t, appSettings
  ]);

  // Chat Area Props
  const chatAreaProps = useMemo(() => ({
    activeSessionId: chatState.activeSessionId,
    sessionTitle,
    currentChatSettings: chatState.currentChatSettings,
    setAppFileError: chatState.setAppFileError,
    isAppDraggingOver: chatState.isAppDraggingOver,
    isProcessingDrop: chatState.isProcessingDrop,
    handleAppDragEnter: chatState.handleAppDragEnter,
    handleAppDragOver: chatState.handleAppDragOver,
    handleAppDragLeave: chatState.handleAppDragLeave,
    handleAppDrop: chatState.handleAppDrop,
    onNewChat: () => chatState.startNewChat(),
    onOpenSettingsModal: () => uiState.setIsSettingsModalOpen(true),
    onOpenScenariosModal: () => uiState.setIsPreloadedMessagesModalOpen(true),
    onToggleHistorySidebar: () => uiState.setIsHistorySidebarOpen(prev => !prev),
    isLoading: chatState.isLoading,
    currentModelName: getCurrentModelDisplayName(),
    availableModels: chatState.apiModels,
    selectedModelId: chatState.currentChatSettings.modelId || appSettings.modelId,
    onSelectModel: chatState.handleSelectModelInHeader,
    isSwitchingModel: chatState.isSwitchingModel,
    isHistorySidebarOpen: uiState.isHistorySidebarOpen,
    onLoadCanvasPrompt: handleLoadCanvasPromptAndSave,
    isCanvasPromptActive: chatState.currentChatSettings.systemInstruction === CANVAS_SYSTEM_PROMPT,
    isBBoxModeActive: chatState.currentChatSettings.systemInstruction === BBOX_SYSTEM_PROMPT,
    onToggleBBox: handleToggleBBoxMode,
    isKeyLocked: !!chatState.currentChatSettings.lockedApiKey,
    themeId: currentTheme.id,
    modelsLoadingError: null,
    messages: chatState.messages,
    scrollContainerRef: chatState.scrollContainerRef,
    setScrollContainerRef: chatState.setScrollContainerRef,
    onScrollContainerScroll: chatState.onScrollContainerScroll,
    onEditMessage: chatState.handleEditMessage,
    onDeleteMessage: chatState.handleDeleteMessage,
    onRetryMessage: chatState.handleRetryMessage,
    onEditMessageContent: chatState.handleUpdateMessageContent, // Directly pass update handler
    onUpdateMessageFile: chatState.handleUpdateMessageFile,
    showThoughts: chatState.currentChatSettings.showThoughts,
    themeColors: currentTheme.colors,
    baseFontSize: appSettings.baseFontSize,
    expandCodeBlocksByDefault: appSettings.expandCodeBlocksByDefault,
    isMermaidRenderingEnabled: appSettings.isMermaidRenderingEnabled,
    isGraphvizRenderingEnabled: appSettings.isGraphvizRenderingEnabled ?? true,
    onSuggestionClick: (text: string) => handleSuggestionClick('homepage', text),
    onOrganizeInfoClick: (text: string) => handleSuggestionClick('organize', text),
    onFollowUpSuggestionClick: (text: string) => handleSuggestionClick('follow-up', text),
    onTextToSpeech: chatState.handleTextToSpeech,
    onGenerateCanvas: chatState.handleGenerateCanvas,
    ttsMessageId: chatState.ttsMessageId,
    language,
    scrollNavVisibility: chatState.scrollNavVisibility,
    onScrollToPrevTurn: chatState.scrollToPrevTurn,
    onScrollToNextTurn: chatState.scrollToNextTurn,
    appSettings,
    commandedInput: chatState.commandedInput,
    setCommandedInput: chatState.setCommandedInput,
    onMessageSent: () => chatState.setCommandedInput(null),
    selectedFiles: chatState.selectedFiles,
    setSelectedFiles: chatState.setSelectedFiles,
    onSendMessage: (text: string) => chatState.handleSendMessage({ text }),
    isEditing: !!chatState.editingMessageId,
    editMode: chatState.editMode,
    editingMessageId: chatState.editingMessageId,
    setEditingMessageId: chatState.setEditingMessageId,
    onStopGenerating: chatState.handleStopGenerating,
    onCancelEdit: chatState.handleCancelEdit,
    onProcessFiles: chatState.handleProcessAndAddFiles,
    onAddFileById: chatState.handleAddFileById,
    onCancelUpload: chatState.handleCancelFileUpload,
    onTranscribeAudio: chatState.handleTranscribeAudio,
    isProcessingFile: chatState.isAppProcessingFile,
    fileError: chatState.appFileError,
    isImagenModel: chatState.currentChatSettings.modelId?.includes('imagen'),
    isImageEditModel: chatState.currentChatSettings.modelId?.includes('image-preview'),
    aspectRatio: chatState.aspectRatio,
    setAspectRatio: chatState.setAspectRatio,
    imageSize: chatState.imageSize,
    setImageSize: chatState.setImageSize,
    isGoogleSearchEnabled: !!chatState.currentChatSettings.isGoogleSearchEnabled,
    onToggleGoogleSearch: chatState.toggleGoogleSearch,
    isCodeExecutionEnabled: !!chatState.currentChatSettings.isCodeExecutionEnabled,
    onToggleCodeExecution: chatState.toggleCodeExecution,
    isUrlContextEnabled: !!chatState.currentChatSettings.isUrlContextEnabled,
    onToggleUrlContext: chatState.toggleUrlContext,
    isDeepSearchEnabled: !!chatState.currentChatSettings.isDeepSearchEnabled,
    onToggleDeepSearch: chatState.toggleDeepSearch,
    onClearChat: chatState.handleClearCurrentChat,
    onOpenSettings: () => uiState.setIsSettingsModalOpen(true),
    onToggleCanvasPrompt: handleLoadCanvasPromptAndSave,
    onTogglePinCurrentSession: chatState.handleTogglePinCurrentSession,
    onRetryLastTurn: chatState.handleRetryLastTurn,
    onEditLastUserMessage: chatState.handleEditLastUserMessage,
    onOpenLogViewer: () => uiState.setIsLogViewerOpen(true),
    onClearAllHistory: chatState.clearAllHistory,
    isPipSupported: pipState.isPipSupported && appSettings.useCustomApiConfig,
    isPipActive: pipState.isPipActive,
    onTogglePip: pipState.togglePip,
    generateQuadImages: appSettings.generateQuadImages ?? false,
    onToggleQuadImages: () => logic.setAppSettings(prev => ({ ...prev, generateQuadImages: !prev.generateQuadImages })),
    onSetThinkingLevel: handleSetThinkingLevel,
    setCurrentChatSettings: chatState.setCurrentChatSettings,
    onOpenSidePanel: handleOpenSidePanel,
    onUpdateMessageContent: chatState.handleUpdateMessageContent,
    handleUpdateMessageFile: chatState.handleUpdateMessageFile,
    onAddUserMessage: chatState.handleAddUserMessage,
    onLiveTranscript: chatState.handleLiveTranscript,
    t,
  }), [
    chatState, uiState, appSettings, currentTheme, language, t, sessionTitle, 
    pipState, handleLoadCanvasPromptAndSave, handleToggleBBoxMode, handleSuggestionClick, handleSetThinkingLevel, 
    handleOpenSidePanel, getCurrentModelDisplayName
  ]);

  // Merge active chat settings into app settings for the modal so controls reflect current session
  const settingsForModal = useMemo(() => {
    if (chatState.activeSessionId && chatState.currentChatSettings) {
        const {
            modelId, temperature, topP, showThoughts, systemInstruction,
            ttsVoice, thinkingBudget, thinkingLevel, lockedApiKey,
            isGoogleSearchEnabled, isCodeExecutionEnabled, isUrlContextEnabled,
            isDeepSearchEnabled, safetySettings, mediaResolution
        } = chatState.currentChatSettings;

        return { 
            ...appSettings,
            modelId, temperature, topP, showThoughts, systemInstruction,
            ttsVoice, thinkingBudget, thinkingLevel, lockedApiKey,
            isGoogleSearchEnabled, isCodeExecutionEnabled, isUrlContextEnabled,
            isDeepSearchEnabled, safetySettings, mediaResolution
        };
    }
    return appSettings;
  }, [appSettings, chatState.currentChatSettings, chatState.activeSessionId]);

  // App Modals Props
  const appModalsProps = useMemo(() => ({
    isSettingsModalOpen: uiState.isSettingsModalOpen,
    setIsSettingsModalOpen: uiState.setIsSettingsModalOpen,
    appSettings: settingsForModal,
    availableModels: chatState.apiModels,
    handleSaveSettings,
    clearCacheAndReload: chatState.clearCacheAndReload,
    clearAllHistory: chatState.clearAllHistory,
    handleInstallPwa: eventsState.handleInstallPwa,
    installPromptEvent: eventsState.installPromptEvent,
    isStandalone: eventsState.isStandalone,
    handleImportSettings: dataManagement.handleImportSettings,
    handleExportSettings: dataManagement.handleExportSettings,
    handleImportHistory: dataManagement.handleImportHistory,
    handleExportHistory: dataManagement.handleExportHistory,
    handleImportAllScenarios: dataManagement.handleImportAllScenarios,
    handleExportAllScenarios: dataManagement.handleExportAllScenarios,
    isPreloadedMessagesModalOpen: uiState.isPreloadedMessagesModalOpen,
    setIsPreloadedMessagesModalOpen: uiState.setIsPreloadedMessagesModalOpen,
    savedScenarios: chatState.savedScenarios,
    handleSaveAllScenarios: chatState.handleSaveAllScenarios,
    handleLoadPreloadedScenario: chatState.handleLoadPreloadedScenario,
    isExportModalOpen,
    setIsExportModalOpen,
    handleExportChat,
    exportStatus,
    isLogViewerOpen: uiState.isLogViewerOpen,
    setIsLogViewerOpen: uiState.setIsLogViewerOpen,
    currentChatSettings: chatState.currentChatSettings,
    t,
    setAvailableModels: chatState.setApiModels,
  }), [
    uiState, settingsForModal, chatState, eventsState, dataManagement,
    isExportModalOpen, exportStatus, handleExportChat, handleSaveSettings, t
  ]);

  return { sidebarProps, chatAreaProps, appModalsProps };
};
