


import { useMemo } from 'react';
import { useAppLogic } from '../useAppLogic';
import { CANVAS_SYSTEM_PROMPT, BBOX_SYSTEM_PROMPT, HD_GUIDE_SYSTEM_PROMPT } from '../../../constants/appConstants';

export const useChatAreaProps = (logic: ReturnType<typeof useAppLogic>) => {
  const {
    appSettings,
    chatState,
    uiState,
    pipState,
    currentTheme,
    language,
    t,
    sessionTitle,
    handleLoadCanvasPromptAndSave,
    handleToggleBBoxMode,
    handleToggleGuideMode,
    handleSuggestionClick,
    handleSetThinkingLevel,
    getCurrentModelDisplayName,
    handleOpenSidePanel,
  } = logic;

  return useMemo(() => ({
    activeSessionId: chatState.activeSessionId,
    sessionTitle,
    currentChatSettings: chatState.currentChatSettings,
    setAppFileError: chatState.setAppFileError,
    isAppDraggingOver: chatState.isAppDraggingOver,
    isProcessingDrop: chatState.isProcessingDrop,
    handleAppDragEnter: chatState.handleAppDragEnter,
    handleAppDragOver: chatState.handleAppDragOver,
    handleAppDragLeave: chatState.handleAppDragLeave,
    handleAppDrop: chatState.handleAppDrop,
    onNewChat: () => chatState.startNewChat(),
    onOpenSettingsModal: () => uiState.setIsSettingsModalOpen(true),
    onOpenScenariosModal: () => uiState.setIsPreloadedMessagesModalOpen(true),
    onToggleHistorySidebar: () => uiState.setIsHistorySidebarOpen(prev => !prev),
    isLoading: chatState.isLoading,
    currentModelName: getCurrentModelDisplayName(),
    availableModels: chatState.apiModels,
    selectedModelId: chatState.currentChatSettings.modelId || appSettings.modelId,
    onSelectModel: chatState.handleSelectModelInHeader,
    isSwitchingModel: chatState.isSwitchingModel,
    isHistorySidebarOpen: uiState.isHistorySidebarOpen,
    onLoadCanvasPrompt: handleLoadCanvasPromptAndSave,
    isCanvasPromptActive: chatState.currentChatSettings.systemInstruction === CANVAS_SYSTEM_PROMPT,
    isBBoxModeActive: chatState.currentChatSettings.systemInstruction === BBOX_SYSTEM_PROMPT,
    isGuideModeActive: chatState.currentChatSettings.systemInstruction === HD_GUIDE_SYSTEM_PROMPT,
    onToggleBBox: handleToggleBBoxMode,
    onToggleGuide: handleToggleGuideMode,
    isKeyLocked: !!chatState.currentChatSettings.lockedApiKey,
    themeId: currentTheme.id,
    modelsLoadingError: null,
    messages: chatState.messages,
    scrollContainerRef: chatState.scrollContainerRef,
    setScrollContainerRef: chatState.setScrollContainerRef,
    onScrollContainerScroll: chatState.onScrollContainerScroll,
    onEditMessage: chatState.handleEditMessage,
    onDeleteMessage: chatState.handleDeleteMessage,
    onRetryMessage: chatState.handleRetryMessage,
    onEditMessageContent: chatState.handleUpdateMessageContent, // Directly pass update handler
    onUpdateMessageFile: chatState.handleUpdateMessageFile,
    showThoughts: chatState.currentChatSettings.showThoughts,
    baseFontSize: appSettings.baseFontSize,
    expandCodeBlocksByDefault: appSettings.expandCodeBlocksByDefault,
    isMermaidRenderingEnabled: appSettings.isMermaidRenderingEnabled,
    isGraphvizRenderingEnabled: appSettings.isGraphvizRenderingEnabled ?? true,
    onSuggestionClick: (text: string) => handleSuggestionClick('homepage', text),
    onOrganizeInfoClick: (text: string) => handleSuggestionClick('organize', text),
    onFollowUpSuggestionClick: (text: string) => handleSuggestionClick('follow-up', text),
    onTextToSpeech: chatState.handleTextToSpeech,
    onGenerateCanvas: chatState.handleGenerateCanvas,
    onContinueGeneration: chatState.handleContinueGeneration,
    ttsMessageId: chatState.ttsMessageId,
    onQuickTTS: chatState.handleQuickTTS,
    language,
    scrollNavVisibility: chatState.scrollNavVisibility,
    onScrollToPrevTurn: chatState.scrollToPrevTurn,
    onScrollToNextTurn: chatState.scrollToNextTurn,
    appSettings,
    commandedInput: chatState.commandedInput,
    setCommandedInput: chatState.setCommandedInput,
    onMessageSent: () => chatState.setCommandedInput(null),
    selectedFiles: chatState.selectedFiles,
    setSelectedFiles: chatState.setSelectedFiles,
    onSendMessage: (text: string, options?: { isFastMode?: boolean }) => chatState.handleSendMessage({ text, ...options }),
    isEditing: !!chatState.editingMessageId,
    editMode: chatState.editMode,
    editingMessageId: chatState.editingMessageId,
    setEditingMessageId: chatState.setEditingMessageId,
    onStopGenerating: chatState.handleStopGenerating,
    onCancelEdit: chatState.handleCancelEdit,
    onProcessFiles: chatState.handleProcessAndAddFiles,
    onAddFileById: chatState.handleAddFileById,
    onCancelUpload: chatState.handleCancelFileUpload,
    onTranscribeAudio: chatState.handleTranscribeAudio,
    isProcessingFile: chatState.isAppProcessingFile,
    fileError: chatState.appFileError,
    isImagenModel: chatState.currentChatSettings.modelId?.includes('imagen'),
    isImageEditModel: chatState.currentChatSettings.modelId?.includes('image-preview'),
    aspectRatio: chatState.aspectRatio,
    setAspectRatio: chatState.setAspectRatio,
    imageSize: chatState.imageSize,
    setImageSize: chatState.setImageSize,
    isGoogleSearchEnabled: !!chatState.currentChatSettings.isGoogleSearchEnabled,
    onToggleGoogleSearch: chatState.toggleGoogleSearch,
    isCodeExecutionEnabled: !!chatState.currentChatSettings.isCodeExecutionEnabled,
    onToggleCodeExecution: chatState.toggleCodeExecution,
    isUrlContextEnabled: !!chatState.currentChatSettings.isUrlContextEnabled,
    onToggleUrlContext: chatState.toggleUrlContext,
    isDeepSearchEnabled: !!chatState.currentChatSettings.isDeepSearchEnabled,
    onToggleDeepSearch: chatState.toggleDeepSearch,
    onClearChat: chatState.handleClearCurrentChat,
    onOpenSettings: () => uiState.setIsSettingsModalOpen(true),
    onToggleCanvasPrompt: handleLoadCanvasPromptAndSave,
    onTogglePinCurrentSession: chatState.handleTogglePinCurrentSession,
    onRetryLastTurn: chatState.handleRetryLastTurn,
    onEditLastUserMessage: chatState.handleEditLastUserMessage,
    onOpenLogViewer: () => uiState.setIsLogViewerOpen(true),
    onClearAllHistory: chatState.clearAllHistory,
    isPipSupported: pipState.isPipSupported && appSettings.useCustomApiConfig,
    isPipActive: pipState.isPipActive,
    onTogglePip: pipState.togglePip,
    generateQuadImages: appSettings.generateQuadImages ?? false,
    onToggleQuadImages: () => logic.setAppSettings(prev => ({ ...prev, generateQuadImages: !prev.generateQuadImages })),
    onSetThinkingLevel: handleSetThinkingLevel,
    setCurrentChatSettings: chatState.setCurrentChatSettings,
    onOpenSidePanel: handleOpenSidePanel,
    onUpdateMessageContent: chatState.handleUpdateMessageContent,
    handleUpdateMessageFile: chatState.handleUpdateMessageFile,
    onAddUserMessage: chatState.handleAddUserMessage,
    onLiveTranscript: chatState.handleLiveTranscript,
    t,
  }), [
    chatState, uiState, appSettings, currentTheme, language, t, sessionTitle, 
    pipState, handleLoadCanvasPromptAndSave, handleToggleBBoxMode, handleToggleGuideMode, handleSuggestionClick, handleSetThinkingLevel, 
    handleOpenSidePanel, getCurrentModelDisplayName, logic.setAppSettings
  ]);
};